services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./setup/keycloak/test-realm.json:/opt/keycloak/data/import/test-realm.json
    command:
      - "start-dev --import-realm"
    ports:
      - "8080:8080"